<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { computed, shallowRef } from 'vue'
import type { ApplicationDto } from '@/api/social'
import { acceptApplication, getApplication, rejectApplication } from '@/api/social'
import AppHeader from '@/components/business/AppHeader.vue'
import AsyncState from '@/components/ui/AsyncState.vue'
const application=shallowRef<ApplicationDto|null>(null),loading=shallowRef(true),working=shallowRef(false),error=shallowRef('')
const rows=computed(()=>application.value?.questions.map(q=>({slot:q.slot,question:q.text,publisher:application.value?.publisherAnswers.find(a=>a.slot===q.slot)?.text||'—',applicant:application.value?.applicantAnswers.find(a=>a.slot===q.slot)?.text||'—'}))||[])
function avatarOf(publicId?:string){const seed=publicId||'tago';const index=Array.from(seed).reduce((sum,char)=>sum+char.charCodeAt(0),0)%7;return `/static/avatars/u${index}.png`}
async function load(id:string){loading.value=true;error.value='';try{application.value=await getApplication(id)}catch(cause){error.value=cause instanceof Error?cause.message:'申请详情加载失败'}finally{loading.value=false}}
async function accept(){if(!application.value)return;working.value=true;try{const result=await acceptApplication(application.value.id);uni.redirectTo({url:`/pages/chat/index?id=${encodeURIComponent(result.conversationId)}`})}finally{working.value=false}}
async function reject(){if(!application.value)return;working.value=true;try{application.value=await rejectApplication(application.value.id);uni.showToast({title:'已婉拒这次申请',icon:'none'})}finally{working.value=false}}
function goBack(){uni.navigateBack()} onLoad(q=>{const id=typeof q?.id==='string'?q.id:'';if(id)load(id);else{loading.value=false;error.value='缺少申请 ID'}})
</script>
<template><view class="tago-page tago-page--detail compare-page"><AppHeader back title="认识申请" subtitle="看看你们是否期待同一件事" @back="goBack"/><AsyncState :loading="loading" :error="error" :empty="!application" @retry="application&&load(application.id)"><section v-if="application" class="intro"><view><image :src="avatarOf(application.publisherIdentity.publicId)" mode="aspectFill"/><b>{{ application.publisherIdentity.displayName }}</b><small>Tag 发布者</small></view><text>×</text><view><image :src="avatarOf(application.applicantIdentity.publicId)" mode="aspectFill"/><b>{{ application.applicantIdentity.displayName }}</b><small>想认识你的人</small></view></section><section v-if="application" class="tag-snapshot"><text># {{ application.tag.body }}</text><image src="/static/stickers/books.png" mode="aspectFit"/></section><section class="compare-list"><article v-for="row in rows" :key="row.slot"><h2><b>Q{{ row.slot }}</b>{{ row.question }}</h2><view class="answer answer--mine"><small>{{ application?.publisherIdentity.displayName }}</small><text>{{ row.publisher }}</text></view><view class="answer answer--theirs"><small>{{ application?.applicantIdentity.displayName }}</small><text>{{ row.applicant }}</text></view></article></section><view v-if="application?.state==='PENDING'" class="actions"><button class="decline" :disabled="working" @click="reject">暂时不了</button><button class="accept" :loading="working" @click="accept">认识 TA</button></view><view v-else-if="application" class="finished">当前申请状态：{{ {ACCEPTED:'已接受',REJECTED:'已婉拒',EXPIRED:'已过期'}[application.state]||'已结束' }}</view></AsyncState></view></template>
<style scoped lang="scss">.intro{display:grid;grid-template-columns:1fr 50rpx 1fr;align-items:center;padding:22rpx 28rpx;border-radius:24rpx;background:rgba(255,253,247,.86);box-shadow:var(--tago-shadow);text-align:center}.intro>view{display:flex;align-items:center;flex-direction:column}.intro image{width:78rpx;height:78rpx;margin-bottom:8rpx;border:5rpx solid #fff;border-radius:50%;box-shadow:0 5rpx 13rpx rgba(38,64,54,.12)}.intro b{font-size:25rpx}.intro small{margin-top:5rpx;color:var(--tago-muted);font-size:17rpx}.intro>text{color:var(--tago-accent);font-size:36rpx}.tag-snapshot{position:relative;display:flex;align-items:center;min-height:112rpx;margin:20rpx 0;padding:24rpx 146rpx 24rpx 30rpx;border-radius:17rpx 28rpx;background:var(--tago-note-yellow);font-size:26rpx;font-weight:850;line-height:1.5;transform:rotate(-.4deg)}.tag-snapshot image{position:absolute;right:16rpx;width:124rpx;height:94rpx;transform:rotate(4deg)}.compare-list{display:flex;flex-direction:column;gap:18rpx}.compare-list article{padding:24rpx;border-radius:24rpx;background:rgba(255,253,247,.88);box-shadow:0 7rpx 20rpx rgba(39,68,56,.07)}.compare-list h2{display:grid;grid-template-columns:50rpx 1fr;gap:8rpx;margin:0 0 16rpx;font-size:23rpx;line-height:1.45}.compare-list h2 b{color:var(--tago-primary)}.answer{display:grid;grid-template-columns:145rpx 1fr;gap:12rpx;margin-top:9rpx;padding:15rpx 18rpx;border-radius:15rpx;font-size:21rpx;line-height:1.55}.answer--mine{background:var(--tago-note-green)}.answer--theirs{background:var(--tago-note-blue)}.answer small{color:var(--tago-muted);font-size:17rpx}.actions{display:grid;grid-template-columns:1fr 1.35fr;gap:14rpx;margin:25rpx 0;padding:12rpx;border-radius:999rpx;background:rgba(248,244,233,.9)}.actions button{height:76rpx;border-radius:999rpx;font-size:24rpx;line-height:76rpx}.actions button::after{border:0}.decline{color:var(--tago-primary);border:1px solid var(--tago-primary);background:#fff}.accept{color:#fff;background:var(--tago-primary)}.finished{margin:25rpx;padding:22rpx;color:var(--tago-muted);text-align:center}.answer text{min-width:0}@media(max-width:360px){.answer{grid-template-columns:1fr}.answer small{font-weight:800}}</style>
